# Generated by Django 4.0 on 2022-02-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='video_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.CharField(max_length=500)),
                ('cover_photo', models.ImageField(upload_to='')),
                ('video_desc', models.CharField(max_length=500)),
            ],
        ),
    ]
