# Generated by Django 4.0 on 2022-02-09 10:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video_data',
            name='cover_photo',
        ),
        migrations.AddField(
            model_name='video_data',
            name='cover_photo_url',
            field=models.CharField(default='None', max_length=5000),
        ),
        migrations.AddField(
            model_name='video_data',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 9, 10, 45, 34, 706856, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='video_data',
            name='video_desc',
            field=models.CharField(default='None', max_length=5000),
        ),
        migrations.AlterField(
            model_name='video_data',
            name='video_url',
            field=models.CharField(default='None', max_length=5000),
        ),
    ]
