# Generated by Django 4.0 on 2022-02-09 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_remove_video_data_cover_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video_data',
            name='date_created',
        ),
    ]
