# Generated by Django 4.0 on 2022-02-15 08:23

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_rename_video_desc_video_data_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='unique_id',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='video_data',
            name='cover_photo_url',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='video_data',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 15, 8, 23, 41, 284624, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='video_data',
            name='title',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='video_data',
            name='video_url',
            field=models.CharField(max_length=5000),
        ),
        migrations.AddField(
            model_name='video_data',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='API.unique_id'),
        ),
    ]
