# Generated by Django 4.0 on 2022-02-16 18:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_unique_id_alter_video_data_cover_photo_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video_data',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='video_data',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 16, 18, 3, 52, 511226, tzinfo=utc)),
        ),
    ]
