# Generated by Django 4.0 on 2022-02-21 09:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_remove_video_data_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video_data',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='API.unique_id'),
        ),
        migrations.AlterField(
            model_name='video_data',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 21, 9, 10, 1, 657082, tzinfo=utc)),
        ),
    ]
