# Generated by Django 4.0 on 2022-02-25 13:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_alter_unique_id_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video_data',
            name='cover_photo_url',
        ),
        migrations.AlterField(
            model_name='video_data',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 25, 13, 24, 58, 464898, tzinfo=utc)),
        ),
    ]
