# Generated by Django 4.0 on 2022-02-28 05:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0011_remove_video_data_cover_photo_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video_data',
            name='title',
        ),
        migrations.AlterField(
            model_name='video_data',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 28, 5, 35, 27, 884130, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='video_data',
            name='video_url',
            field=models.URLField(max_length=5000),
        ),
    ]
