# Generated by Django 4.0 on 2022-03-01 08:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0012_remove_video_data_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video_data',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 1, 8, 51, 8, 593539, tzinfo=utc)),
        ),
    ]
